### PR TITLE
Clarify intent in section on persistence

### PR DESCRIPTION
**Pull request by dhh1128**
Signed-off-by: Daniel Hardman <daniel.hardman@gmail.com>

***
<a href="https://pr-preview.s3.amazonaws.com/dhh1128/did-spec/pull/254.html" title="Last updated on Aug 8, 2019, 4:54 PM UTC (4c1e4ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/254/bd4f2fa...dhh1128:4c1e4ba.html" title="Last updated on Aug 8, 2019, 4:54 PM UTC (4c1e4ba)">Diff</a>

### CODE REVIEW

**Comment by dhh1128** [comment]
As I did a final editorial pass, I found this section that was not sufficiently clear to my fresh eyes. So I'm just suggesting an extra sentence and a half to make it clearer.

**Comment by rhiaro** [comment]
The last 'should' may need rewording so it isn't accidentally misconstrued as normative language. Something like "is not supposed to be repurposed"?

**Comment by peacekeeper** [comment]
Agree with @rhiaro , otherwise this looks like a good clarification to me.

**Comment by dhh1128** [comment]
Updated as @rhiaro suggested.

**Pull request merged**
