### PR TITLE
add missing comma

### PR DESCRIPTION
**Pull request by TallTed**
***
<a href="https://pr-preview.s3.amazonaws.com/TallTed/did-spec/pull/266.html" title="Last updated on Aug 12, 2019, 4:12 PM UTC (9b85571)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c-ccg/did-spec/266/238c65d...TallTed:9b85571.html" title="Last updated on Aug 12, 2019, 4:12 PM UTC (9b85571)">Diff</a>

### CODE REVIEW

**Comment by peacekeeper** [comment]
Thanks @TallTed, since we've already created the [CGFR](https://w3c-ccg.github.io/did-spec/CGFR/2019-08-10/), we'll leave this open for now until the DID WG is formed.

**Comment by brentzundel** [comment]
This repo is scheduled to be archived. The work has moved to [the DID WG](https://github.com/w3c/did-spec/pulls).
The artifacts in the DID WG repository (including the context document) share commit history with this repo, so it should be possible to raise this PR [against that repo](https://github.com/w3c/did-spec/pulls).

**Comment by TallTed** [comment]
@brentzundel @peacekeeper @rhiaro - It does not seem to be possible to directly [compare my fork against the new repo](https://github.com/w3c/did-spec/compare/gh-pages...TallTed:patch-1).  This PR is tiny, so I can easily redo it -- but that may not be so for all the other in-flight contributions.

**Comment by msporny** [comment]
Finally got around to fixing this in the DID core spec: https://github.com/w3c/did-core/commit/e59f86d3f1c520f337484dd6bdb7d7e929cd9b68

**Pull request closed without merging**
