### PR TITLE
Added IETF registration of DID URI Scheme. Fixes #73.

### LINKED ISSUE #73: Register DID URI Scheme
We should register the DID URI scheme here:

https://www.iana.org/assignments/uri-schemes/uri-schemes.xml

### PR DESCRIPTION
**Pull request by msporny**
This is a complete registration template for IETF registration. I've already submitted it to IETF as a provisional registration, which means we can update it as the spec matures.

### CODE REVIEW

**Comment by msporny** [comment]
I filled all those sections out and THEN saw the part that says that those sections are no longer required:

https://tools.ietf.org/html/rfc7595#section-7.4

> The previous version of this specification required the following additional fields in a scheme registration request.  These fields are no longer part of the template.  The answers instead belong in the scheme specification.

**Comment by kimdhamilton** [comment]
sounds good

**Comment by msporny** [comment]
The IETF Provisional URI Scheme Registration has been accepted: https://lists.w3.org/Archives/Public/public-credentials/2018May/0028.html

**Comment by msporny** [comment]
Merging, because it's already been processed at IETF.

**Comment by peacekeeper** [comment]
Is this an "IETF registration" or an "IANA registration"? Just confused by the file name.

**Pull request merged**
